name MSD O windows lates t
on
push
branches mai n
pull_request
branches mai n
workflow_dispatch
jobs
sample
MSDO runs on windows latest and ubuntu latest
macos latest supporting coming soo n
runs on windows lates t
steps
uses actions/checkout@v 3
uses actions/setup dotnet@v 3
with
dotnet version
5.0.x
6.0.x
Run analyzers
name Ru n Microsof t Securit y DevOp s Analysi s
uses microsoft/security devops action@previe w
id msd o
Upload alerts to the Security ta b
name Uploa d alert s t o Securit y ta b
uses github/codeql action/upload sarif@v 2
with
sarif_file steps.msdo.outputs.sarifFil e
